spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=order-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8000
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/orders/**

spring.cloud.gateway.server.webmvc.routes[1].id=inventory-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8001
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/inventory/**